name: Issue Commenter

permissions:
  issues: write

on:
  issues:
    types: [opened, edited]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Generate comment
        id: comment-body
        run: |
          echo "COMMENT<<EOF" >> $GITHUB_ENV
          echo "👋 Thanks for opening this issue, we’ll look into it shortly!" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Find existing comment
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '👋 Thanks for opening this issue'

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: ${{ env.COMMENT }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace

